# Generated by Django 3.0.7 on 2021-03-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50)),
                ('hostname', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'hosts',
                'ordering': ('-id',),
            },
        ),
    ]
